services:
  attacker:
    build:
      context: .
      dockerfile: Dockerfile1.node
      args:
        USERNAME: attacker
        PASSWORD: attacker
    container_name: attacker
    hostname: attacker
    tty: true
    networks:
      net_a:
        ipv4_address: 172.28.0.10
    cap_add:
      - NET_ADMIN
    environment:
      - GATEWAY=172.28.0.254

  pc1:
    build:
      context: .
      dockerfile: Dockerfile2.node
      args:
        USERNAME: JWick
        PASSWORD: pickles
    container_name: pc1
    hostname: JWickPC
    tty: true
    networks:
      net_a:
        ipv4_address: 172.28.0.11
    cap_add:
      - NET_ADMIN
    environment:
      - GATEWAY=172.28.0.254

  router:
    build:
      context: .
      dockerfile: Dockerfile.router
    container_name: router
    tty: true
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      net_a:
        ipv4_address: 172.28.0.254
      net_b:
        ipv4_address: 172.29.0.254

  pc2:
    build:
      context: .
      dockerfile: Dockerfile3.node
      args:
        USERNAME: admin
        PASSWORD: 1qaz2wsx
    container_name: pc2
    hostname: adminPC
    tty: true
    networks:
      net_b:
        ipv4_address: 172.29.0.11
    cap_add:
      - NET_ADMIN
    environment:
      - GATEWAY=172.29.0.254

networks:
  net_a:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

  net_b:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
          gateway: 172.29.0.1

